site_name: HoneyBee
theme:
  name: material
  language: pt-BR
  features: 
     - toc.integrate
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    - scheme: slate 
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

extra:
  extra_css:
  - style.css

copyright: |
  &copy; 2024 - GJR

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav: 
  - In√≠cio: index.md
  - Documentos PDF: 
      - Weekend: Documentos/weekend.md
      - Past Lives 1: Documentos/pastlives1.md
  - Imagens:
      - Imagens: Imagens/imagens.md
  - Documentos Word:
      - Past Lives 2: Documentos/pastlives2.md
  - Programas:
      - Programas: Programas/programas.md